package com.femi.femi_poc.model.json;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FemiAgreementEntitlement2 implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String id;
   private java.lang.String expose;

   private java.util.Date currentDate;

   private com.femi.femi_poc.model.json.ListOfFemiAgreementLineItemAsset listOfFemiAgreementLineItemAsset;

   private java.lang.String maximumServices;

   private java.lang.String name4;

   public FemiAgreementEntitlement2()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.String getExpose()
   {
      return this.expose;
   }

   public void setExpose(java.lang.String expose)
   {
      this.expose = expose;
   }

   public java.util.Date getCurrentDate()
   {
      return this.currentDate;
   }

   public void setCurrentDate(java.util.Date currentDate)
   {
      this.currentDate = currentDate;
   }

   public com.femi.femi_poc.model.json.ListOfFemiAgreementLineItemAsset getListOfFemiAgreementLineItemAsset()
   {
      return this.listOfFemiAgreementLineItemAsset;
   }

   public void setListOfFemiAgreementLineItemAsset(
         com.femi.femi_poc.model.json.ListOfFemiAgreementLineItemAsset listOfFemiAgreementLineItemAsset)
   {
      this.listOfFemiAgreementLineItemAsset = listOfFemiAgreementLineItemAsset;
   }

   public java.lang.String getMaximumServices()
   {
      return this.maximumServices;
   }

   public void setMaximumServices(java.lang.String maximumServices)
   {
      this.maximumServices = maximumServices;
   }

   public java.lang.String getName4()
   {
      return this.name4;
   }

   public void setName4(java.lang.String name4)
   {
      this.name4 = name4;
   }

   public FemiAgreementEntitlement2(
         java.lang.String id,
         java.lang.String expose,
         java.util.Date currentDate,
         com.femi.femi_poc.model.json.ListOfFemiAgreementLineItemAsset listOfFemiAgreementLineItemAsset,
         java.lang.String maximumServices, java.lang.String name4)
   {
      this.id = id;
      this.expose = expose;
      this.currentDate = currentDate;
      this.listOfFemiAgreementLineItemAsset = listOfFemiAgreementLineItemAsset;
      this.maximumServices = maximumServices;
      this.name4 = name4;
   }

}