package com.femi.femi_poc.model.json;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FemiAgreementEntitlement2 implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public FemiAgreementEntitlement2() {
    }

}