package com.femi.femi_poc.model.json;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FemiAgreementEntitlement2 implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String id;
   private java.lang.String expose;

   private java.util.Date currentDate;

   public FemiAgreementEntitlement2()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.String getExpose()
   {
      return this.expose;
   }

   public void setExpose(java.lang.String expose)
   {
      this.expose = expose;
   }

   public java.util.Date getCurrentDate()
   {
      return this.currentDate;
   }

   public void setCurrentDate(java.util.Date currentDate)
   {
      this.currentDate = currentDate;
   }

   public FemiAgreementEntitlement2(java.lang.String id, java.lang.String expose,
         java.util.Date currentDate)
   {
      this.id = id;
      this.expose = expose;
      this.currentDate = currentDate;
   }

}