package com.femi.femi_poc.rules;


rule "init-data"
	dialect "java"
	salience 1000
	when
	
	then
	    com.femi.femi_poc.model.GeneralData generalData = new com.femi.femi_poc.model.GeneralData();
	    kcontext.getKnowledgeRuntime().insert(generalData);
end



rule "fetch-data-for-contact"
	dialect "java"
	salience 1000
	when
	   com.femi.femi_poc.model.Applicant($id: id, $area: area, isFetchContactDataFromProxy==true)
	then
		System.out.println("femi rules version 5.3");
		java.util.List<com.femi.femi_poc.model.json.FemiAgreementEntitlement> femiAgreementEntitlementList = com.femi.femi_poc.AccessProxy.fetchContactDetails($id, $area);
		System.out.println("proxy returned " + femiAgreementEntitlementList.size() + " femiAgreementEntitlement objects");
		for (com.femi.femi_poc.model.json.FemiAgreementEntitlement femiAgreementEntitlement: femiAgreementEntitlementList ){
	    	System.out.println("femiAgreementEntitlement: " + femiAgreementEntitlement);
		    kcontext.getKnowledgeRuntime().insert(femiAgreementEntitlement);
		}

end

rule "print-FemiAgreementEntitlement"
	dialect "java"
	salience 1000
	when
	   $femiAgreementEntitlement: com.femi.femi_poc.model.json.FemiAgreementEntitlement()
	then
		System.out.println("new femiAgreementEntitlement inserted: " + $femiAgreementEntitlement.getId() + " date: " + $femiAgreementEntitlement.getQualificationDate2() +
		", expose: " + $femiAgreementEntitlement.getExpose());
end
