package com.femi.femi_poc.rules;

rule "fetch-data-for-contact"
	dialect "java"
	salience 1000
	when
	   com.femi.femi_poc.model.Applicant($id: id, $area: area, isFetchContactDataFromProxy==true)
	then
		System.out.println("femi rules version 2.4");
/*		java.util.List<com.femi.femi_poc.model.json.FemiAgreementEntitlement> femiAgreementEntitlementList = com.femi.femi_poc.AccessProxy.fetchContactDetails($id, $area);
		for (com.femi.femi_poc.model.json.FemiAgreementEntitlement femiAgreementEntitlement: femiAgreementEntitlementList ){
	    	System.out.println("femiAgreementEntitlement: " + femiAgreementEntitlement);
		    femiAgreementEntitlement.setCurrentDate(new java.util.Date());
		    kcontext.getKnowledgeRuntime().insert(femiAgreementEntitlement);
		}
*/
end

rule "print-FemiAgreementEntitlement"
	dialect "java"
	salience 1000
	when
	   $femiAgreementEntitlement: com.femi.femi_poc.model.json.FemiAgreementEntitlement()
	then
		System.out.println("new femiAgreementEntitlement inserted: " + $femiAgreementEntitlement.getId());
end
