package com.femi.femi_poc.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Applicant implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("id")
   private java.lang.String id;
   @org.kie.api.definition.type.Label("area")
   private java.lang.String area;

   private boolean isFetchContactDataFromProxy;

   public Applicant()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.String getArea()
   {
      return this.area;
   }

   public void setArea(java.lang.String area)
   {
      this.area = area;
   }

   public boolean isIsFetchContactDataFromProxy()
   {
      return this.isFetchContactDataFromProxy;
   }

   public void setIsFetchContactDataFromProxy(
         boolean isFetchContactDataFromProxy)
   {
      this.isFetchContactDataFromProxy = isFetchContactDataFromProxy;
   }

   public Applicant(java.lang.String id, java.lang.String area,
         boolean isFetchContactDataFromProxy)
   {
      this.id = id;
      this.area = area;
      this.isFetchContactDataFromProxy = isFetchContactDataFromProxy;
   }

}