package com.femi.femi_poc.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Applicant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "id")
	private java.lang.String id;
	@org.kie.api.definition.type.Label(value = "area")
	private java.lang.String area;

	public Applicant() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getArea() {
		return this.area;
	}

	public void setArea(java.lang.String area) {
		this.area = area;
	}

	public Applicant(java.lang.String id, java.lang.String area) {
		this.id = id;
		this.area = area;
	}

}