package com.femi.femi_poc.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class GeneralData implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public GeneralData() {
    }

}