package com.femi.femi_poc.model;


/**
 * This class was automatically generated by the data modeler tool.
 */

public class RequestResult implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.femi.femi_poc.model.json.FemiAgreementEntitlement> femiAgreementEntitlementList = new java.util.ArrayList<com.femi.femi_poc.model.json.FemiAgreementEntitlement>();

	public RequestResult() {
	}

	public java.util.List<com.femi.femi_poc.model.json.FemiAgreementEntitlement> getFemiAgreementEntitlementList() {
		return this.femiAgreementEntitlementList;
	}

	public void setFemiAgreementEntitlementList(
			java.util.List<com.femi.femi_poc.model.json.FemiAgreementEntitlement> femiAgreementEntitlementList) {
		this.femiAgreementEntitlementList = femiAgreementEntitlementList;
	}

	public RequestResult(
			java.util.List<com.femi.femi_poc.model.json.FemiAgreementEntitlement> femiAgreementEntitlementList) {
		this.femiAgreementEntitlementList = femiAgreementEntitlementList;
	}
	
	public void addFemiAgreementEntitlement(com.femi.femi_poc.model.json.FemiAgreementEntitlement femiAgreementEntitlement){
	   femiAgreementEntitlementList.add(femiAgreementEntitlement);
	}

}