package com.femi.femi_poc.rules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class IsAllowToDrive implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public IsAllowToDrive() {
    }

}